#pragma once
#include <cstdint>

enum class TextureID : std::uint8_t
{
    BLOCK_STONE1,
    BLOCK_STONE2,
    BLOCK_STONE3,
    BLOCK_ROPE_START,
    BLOCK_ROPE_MAIN,
    BLOCK_ROPE_END,
    BLOCK_SKY,
    BLOCK_SAND,
    BLOCK_TRAPDOOR,
    FRED_LEFT_STANDING,
    FRED_LEFT_BIG_STEP,
    FRED_LEFT_SMALL_STEP,
    FRED_RIGHT_STANDING,
    FRED_RIGHT_BIG_STEP,
    FRED_RIGHT_SMALL_STEP,
    FRED_LEFT_CLIMBING1,
    FRED_LEFT_CLIMBING2,
    FRED_RIGHT_CLIMBING1,
    FRED_RIGHT_CLIMBING2,
    FRED_LEFT_SHOOTING,
    FRED_RIGHT_SHOOTING,
    FRED_LEFT_JUMP_SHOOTING,
    FRED_RIGHT_JUMP_SHOOTING,
    COUNT
};
