name: "Build"
on:
  push:
    branches: main
  pull_request:
    branches: main
    types:
      - opened
      - edited
      - synchronize

jobs:
  build_linux:
    name: 'Linux build'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout source'
        uses: actions/checkout@v4
      - name: 'Install SDL2'
        uses: './.github/actions/setup-sdl'
        with:
          sdl_version: '2.30.3'
      - name: 'Install SDL2_image'
        uses: './.github/actions/setup-sdl_image'
        with:
          sdl_image_version: '2.8.2'
      - name: 'Configure and build'
        run: |
          cmake -G Ninja -S . -B build
          cmake --build build --verbose

  build_windows:
    name: 'Windows build'
    runs-on: windows-latest
    steps:
      - name: 'Checkout source'
        uses: actions/checkout@v4

      - name: Download SDL2
        run: |
          Invoke-WebRequest "https://www.libsdl.org/release/SDL2-devel-2.30.3-VC.zip" -OutFile "SDL2.zip"
          Expand-Archive -Path SDL2.zip -DestinationPath "C:\SDL2"

      - name: Download SDL2_image
        run: |
          Invoke-WebRequest "https://github.com/libsdl-org/SDL_image/releases/download/release-2.8.2/SDL2_image-devel-2.8.2-VC.zip" -OutFile "SDL2_image.zip"
          Expand-Archive -Path SDL2_image.zip -DestinationPath "C:\SDL2_image"

      - name: 'Configure and build - 64 bit binary'
        run: |
          mkdir build
          mkdir build\win64
          cmake -G "Visual Studio 17 2022" -A x64 "-DCMAKE_PREFIX_PATH=C:\SDL2;C:\SDL2_image" -S . -B build\win64
          cmake --build build\win64 --config Release --verbose
          cd build\win64
          cpack -G ZIP --config CPackConfig.cmake

      - name: 'Archive 64 bit binary'
        uses: actions/upload-artifact@v4
        with:
          name: retro-fred-win64
          if-no-files-found: error
          path: build/win64/retro-fred-*-win64.zip
