name: "Ubuntu build"
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout source'
        uses: actions/checkout@v4
      - name: 'Install SDL2'
        uses: './.github/actions/setup-sdl'
        with:
          sdl_version: '2.30.3'
      - name: 'Install SDL2_image'
        uses: './.github/actions/setup-sdl_image'
        with:
          sdl_image_version: '2.8.2'
      - name: 'Configure and build'
        run: |
          cmake -G Ninja -S . -B build
          cmake --build build --verbose
